# Generated by Django 3.1.4 on 2021-01-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210102_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default=1, upload_to='articles/'),
            preserve_default=False,
        ),
    ]
